name: 'GitHub Actions'

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  tests:
    name: 'tests'
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: bahmutov/npm-install@v1
    - run: npm test

  prettier:
    name: 'prettier'
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: npm run fmt:check
